//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatternDiscovery
{
    using System;
    using System.Collections.Generic;
    
    public partial class stat
    {
        public string Code { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> Up2win { get; set; }
        public Nullable<int> Up4win { get; set; }
        public Nullable<int> Up8win4Stop { get; set; }
        public Nullable<System.DateTime> LastTime { get; set; }
    }
}
