//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatternDiscovery
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_upload
    {
        public string Ric { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<int> offset { get; set; }
        public string period { get; set; }
        public Nullable<double> Open { get; set; }
        public Nullable<double> High { get; set; }
        public Nullable<double> Low { get; set; }
        public Nullable<double> Last { get; set; }
        public Nullable<double> Volume { get; set; }
        public Nullable<double> AvPrice { get; set; }
        public Nullable<double> VWAP { get; set; }
        public Nullable<int> Qty { get; set; }
        public long id { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    }
}
